### ISSUE TITLE
Android.mk:head_pose_det: non-system libraries in linker flags: -latomic

### ISSUE THREAD

**Issue by mohammad-hdiz** [beraldofilippo/android-hpe-library#1]
Hi, when i run %NDK_PATH%\ndk-build.cmd into "jni" folder , i get this error. Anyone can help me ?

`C:\Users\android-hpe-library-master\android-hpe-library-master\jni>%NDK_PATH%\ndk-build.cmd
Android NDK: WARNING:C:/Users/Mohammad/Downloads/android-hpe-library-master/android-hpe-library-master/jni/Android.mk:head_pose_det: non-system libraries in linker flags: -latomic
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
Android NDK: WARNING:C:/Users/Mohammad/Downloads/android-hpe-library-master/android-hpe-library-master/jni/Android.mk:head_pose_det: non-system libraries in linker flags: -latomic
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module
[armeabi-v7a] Compile++ arm  : head_pose_det <= jni_head_pose_det.cpp
[armeabi-v7a] Compile++ arm  : head_pose_det <= imageutils_jni.cpp
[armeabi-v7a] Compile++ arm  : head_pose_det <= rgb2yuv.cpp
[armeabi-v7a] Compile++ arm  : head_pose_det <= yuv2rgb.cpp
[armeabi-v7a] Compile++ arm  : head_pose_det <= bitmap2mat2bitmap.cpp
[armeabi-v7a] Compile++ thumb: dlib <= threads_kernel_shared.cpp
[armeabi-v7a] Compile++ thumb: dlib <= entropy_decoder_kernel_2.cpp
[armeabi-v7a] Compile++ thumb: dlib <= base64_kernel_1.cpp
[armeabi-v7a] Compile++ thumb: dlib <= threads_kernel_1.cpp
[armeabi-v7a] Compile++ thumb: dlib <= threads_kernel_2.cpp
[armeabi-v7a] StaticLibrary  : libdlib.a
[armeabi-v7a] Compile++ thumb: miniglog <= logging.cc
[armeabi-v7a] StaticLibrary  : libminiglog.a
[armeabi-v7a] SharedLibrary  : libhead_pose_det.so
C:/Users/Mohammad/Downloads/android-hpe-library-master/android-hpe-library-master/third_party/OpenCV-android-sdk/sdk/native/jni/../libs/armeabi-v7a/libopencv_calib3d.a(fundam.cpp.o):fundam.cpp:function _GLOBAL__sub_I_fundam.cpp: error: undefined reference to 'std::ios_base::Init::Init()'
C:/Users/Mohammad/Downloads/android-hpe-library-master/android-hpe-library-master/third_party/OpenCV-android-sdk/sdk/native/jni/../libs/armeabi-v7a/libopencv_calib3d.a(fundam.cpp.o):fundam.cpp:function _GLOBAL__sub_I_fundam.cpp: error: undefined reference to 'std::ios_base::Init::~Init()'
C:/Users/Mohammad/Downloads/android-hpe-library-master/android-hpe-library-master/third_party/OpenCV-android-sdk/sdk/native/jni/../libs/armeabi-v7a/libopencv_calib3d.a(rho.cpp.o):rho.cpp:function std::vector<unsigned int, std::allocator<unsigned int> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned int*, std::vector<unsigned int, std::allocator<unsigned int> > >, unsigned int, unsigned int const&): error: undefined reference to 'std::__throw_length_error(char const*)'
C:/Users/Mohammad/Downloads/android-hpe-library-master/android-hpe-library-master/third_party/OpenCV-android-sdk/sdk/native/jni/../libs/armeabi-v7a/libopencv_calib3d.a(solvepnp.cpp.o):solvepnp.cpp:function std::vector<cv::Point3_<double>, std::allocator<cv::Point3_<double> > >::_M_fill_insert(__gnu_cxx::__normal_iterator<cv::Point3_<double>*, std::vector<cv::Point3_<double>, std::allocator<cv::Point3_<double> > > >, unsigned int, cv::Point3_<double> const&): error: undefined reference to 'std::__throw_length_error(char const*)'
C:/Users/Mohammad/Downloads/android-hpe-library-master/android-hpe-library-master/third_party/OpenCV-android-sdk/sdk/native/jni/../libs/armeabi-v7a/libopencv_calib3d.a(solvepnp.cpp.o):solvepnp.cpp:function std::vector<cv::Point_<double>, std::allocator<cv::Point_<double> > >::_M_fill_insert(__gnu_cxx::__normal_iterator<cv::Point_<double>*, std::vector<cv::Point_<double>, std::allocator<cv::Point_<double> > > >, unsigned int, cv::Point_<double> const&): error: undefined reference to 'std::__throw_length_error(char const*)'
tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::invalid_argument::invalid_argument(std::string const&)'
C:/Users/Mohammad/Downloads/android-hpe-library-master/android-hpe-library-master/third_party/OpenCV-android-sdk/sdk/native/jni/../3rdparty/libs/armeabi-v7a/libtbb.a(tbb_misc.cpp.o):tbb_misc.cpp:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::range_error::range_error(std::string const&)'
C:/Users/Mohammad/Downloads/android-hpe-library-master/android-hpe-library-master/third_party/OpenCV-android-sdk/sdk/native/jni/../3rdparty/libs/armeabi-v7a/libtbb.a(tbb_misc.cpp.o):tbb_misc.cpp:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::range_error::range_error(std::string const&)'
C:/Users/Mohammad/Downloads/android-hpe-library-master/android-hpe-library-master/third_party/OpenCV-android-sdk/sdk/native/jni/../3rdparty/libs/armeabi-v7a/libtbb.a(tbb_misc.cpp.o):tbb_misc.cpp:function tbb::internal::throw_exception_v4(tbb::internal::exception_id): error: undefined reference to 'std::invalid_argument::invalid_argument(std::string const&)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [G:/IT/AndroidStudioSdk/AndroidStudio/ndk/21.0.6113669/build//../build/core/build-binary.mk:725: C:/Users/Mohammad/Downloads/android-hpe-library-master/android-hpe-library-master/obj/local/armeabi-v7a/libhead_pose_det.so] Error 1`

**Comment by beraldofilippo** [comment]
Hello, please refer to this https://github.com/beraldofilippo/android-hpe-library/issues/2. It is likely that recent tools have breaking changes and it is not possible to build with those.
