### ISSUE TITLE
Android NDK: android-8 is unsupported. Using minimum supported version android-16.

### ISSUE THREAD

**Issue by mowkee** [beraldofilippo/android-hpe-library#2]
looks like it no longer builds. Do you have any update?

**Comment by beraldofilippo** [comment]
Hey. Sorry to hear that, unfortunately I am no longer active on this project.

It would be great if it could at least be runnable though. Any PR that restores it is welcome.

Thanks.

**Comment by beraldofilippo** [comment]
I have just tried to build it and got a version working. This project is a little old and requires older dependencies, therefore we have to retrieve older versions.

My setup:
### MacOS X Catalina

### NDK
https://developer.android.com/ndk/downloads/index.html > Old Unsupported Versions > Download NDK-r13b 
Use this one to build (MacOs X has some additional security that needs to be taken care of in General > Security & Privacy, on WIndows I do not recall having any issue running that ndk).

### OpenCV
We need to use OpenCV 3.1 Android SDK. Following the link on the official website https://sourceforge.net/projects/opencvlibrary/files/opencv-android/3.1.0/OpenCV-3.1.0-android-sdk.zip/download
Use this one.

Running the command provides you with the .so libraries.

I might have overlooked this part of the documentation, I'll make sure to add these specific steps, I'm not sure it's possible to compile with more recent tooling as there are surely some breaking changes, it will require additional work.

Thanks.
